image: "ruby:2.3"
stages:
  - test
  - build
variables:
  POSTGRES_DB: cloud-task-runner_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 'postgres'
rspec:
  stage: test
  services:
    - postgres:10
  script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib nodejs libpq-dev cmake
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
    - cp config/application.sample.yml config/application.yml
    - cp config/database.sample.yml config/database.yml
    - cp config/secrets.sample.yml config/secrets.yml
    - RAILS_ENV=test bundle exec rake db:setup
    - RAILS_ENV=test bundle exec rspec spec

rubocop:
  stage: test
  script:
    - ruby -v
    - which ruby
    - gem install rubocop
    - rubocop

build:
  stage: build
  only:
    - master
    - develop
  image: "docker:git"
  services:
    - docker:dind
  variables:
    CONTAINER_RELEASE_IMAGE: registry.gitlab.com/moeenzarrinfam/cloud-task-runner:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
