#WEB SERVER
COOKIE_NAME: '_CLOUD_TASK_RUNNER_SESSION'
HOST_NAME: 'localhost'
DATABASE_HOST: 'postgres'
DATABASE_USERNAME: 'postgres'
DATABASE_PASSWORD: 'postgres'
APPLICATION_SECRET_KEY: ''

#MAIL SERVER
MAIL_ADDRESS: 'info@cloud-task-runner.com'
MAIL_SERVER_ADDRESS: 'smtp.mailgun.org'
MAIL_USERNAME: ''
MAIL_PASSWORD: ''

TASK_RUNNING_TIME: '10'
